version: "3.8"

services:
  db:
    image: postgres:13.1
    restart: always
    container_name: db  
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    expose:
      - "5432"
  web:
    image: skhortyuk/foodgram:latest 
    container_name: web
    restart: always
    expose:
      - "8000"
    depends_on:
      - db
    volumes:
      - static_data:/code/static
      - media_data:/code/media
    env_file:
      - ./.env
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:8000"
    depends_on:
      - web
    environment:
      - DOMAIN=${DOMAIN}
    env_file:
      - ./.env
    volumes:
      - static_data:/www/static/
      - media_data:/www/media/
      - ./nginx:/etc/nginx/templates
    

volumes:
  static_data:
  media_data:
  postgres_data:
