# Generated by Django 3.1.4 on 2020-12-16 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(blank=True, choices=[('green', 'green'), ('orange', 'orange'), ('purple', 'purple')], default='', max_length=20),
        ),
    ]
