# Generated by Django 3.1.4 on 2020-12-16 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20201217_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(blank=True, choices=[('green', 'green'), ('orange', 'orange'), ('purple', 'purple'), ('', '')], default='', max_length=20),
        ),
    ]
