# Generated by Django 3.1.4 on 2020-12-18 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20201218_0202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='text',
            new_name='description',
        ),
    ]
